apiVersion: apps/v1
kind: Deployment
metadata:
    name: blog
    labels:
        app: blog
spec:
    selector:
        matchLabels:
            app: blog
    template:
        metadata:
            labels:
                app: blog
        spec:
            containers:
            - name: blog
              image: berwoutv/blog
              imagePullPolicy: Always
              ports:
              - containerPort: 80
              readinessProbe:
                httpGet:
                    path: /
                    port: 80
                initialDelaySeconds: 5
                periodSeconds: 5
            