apiVersion: v1
kind: Service
metadata:
  name: http3-test-frontend
  labels:
    app: http3-test-frontend
spec:
  type: ClusterIP
  selector:
    app: http3-test-frontend
  ports:
    - port: 8080
      targetPort: 80
