apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: main
resources:
- namespace.yaml
- blog-ingress.yaml
- dinner-planner-ingress.yaml
- meal-service-ingress.yaml
- ingredient-service-ingress.yaml
bases:
- ../../services/blog
- ../../services/dinner-planner
- ../../services/ingredient-service
- ../../services/meal-service
- ../../services/mongo-setup