apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: main
images:
- name: berwoutv/blog
  newTag: latest
- name: berwoutv/dinner-planner
  newTag: latest
- name: berwoutv/ingredient-service
  newTag: latest
- name: berwoutv/meal-service
  newTag: latest
- name: berwoutv/mongo-setup
  newTag: latest
resources:
- namespace.yaml
- blog-ingress.yaml
- dinner-planner-ingress.yaml
- meal-service-ingress.yaml
- ingredient-service-ingress.yaml
bases:
- ../../services/blog
- ../../services/dinner-planner
- ../../services/ingredient-service
- ../../services/meal-service
- ../../services/mongo-setup