apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: main
images:
- name: berwoutv/ingredient-service
  newTag: master-9
- name: berwoutv/meal-service
  newTag: master-9
- name: berwoutv/portfolio
  newTag: master-9
- name: berwoutv/blog
  newTag: master-9
resources:
- namespace.yaml
- blog-ingress.yaml
- meal-service-ingress.yaml
- ingredient-service-ingress.yaml
- portfolio-ingress.yaml
bases:
- ../../services/blog
- ../../services/ingredient-service
- ../../services/meal-service
- ../../services/portfolio
