apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prd
resources:
- namespace.yaml
- blog-ingress.yaml
- dinner-ingress.yaml
- meal-ingress.yaml
- ingredients-ingress.yaml
bases:
- ../../services/blog
- ../../services/dinner-planner
- ../../services/ingredient-service
- ../../services/meal-service
- ../../services/mongo-setup