apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: main
images:
  - name: berwoutv/ingredient-service
    newTag: master-57
  - name: berwoutv/meal-service
    newTag: master-57
  - name: berwoutv/portfolio
    newTag: master-57
  - name: berwoutv/animator-pwa
    newTag: master-57
  - name: berwoutv/blog
    newTag: master-57
  - name: berwoutv/o-frontend
    newTag: "3.8"
  - name: berwoutv/o-backend
    newTag: "3.9"
resources:
  - namespace.yaml
  - blog-ingress.yaml
  - meal-service-ingress.yaml
  - ingredient-service-ingress.yaml
  - portfolio-ingress.yaml
  - animator-pwa-ingress.yaml
  - o-frontend-ingress.yaml
  - o-backend-ingress.yaml
  - o-backend-ws-ingress.yaml
bases:
  - ../../services/blog
  - ../../services/ingredient-service
  - ../../services/meal-service
  - ../../services/portfolio
  - ../../services/animator-pwa
  - ../../services/o-frontend
  - ../../services/o-backend
