apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: o-backend-tls
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`orchestra.berwout.nl`) && Path(`/api`)
      kind: Rule
      services:
        - name: o-backend
          port: 8080
