apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: portfolio-tls
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`portfolio.berwout.nl`)
    kind: Rule
    services:
    - name: portfolio
      port: 8080