apiVersion: apps/v1
kind: Deployment
metadata:
  name: o-backend
  labels:
    app: o-backend
spec:
  selector:
    matchLabels:
      app: o-backend
  template:
    metadata:
      labels:
        app: o-backend
    spec:
      containers:
        - name: o-backend
          image: berwoutv/o-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
