apiVersion: apps/v1
kind: Deployment
metadata:
    name: selenium
    labels:
        app: selenium
spec:
    selector:
        matchLabels:
            app: selenium
    template:
        metadata:
            labels:
                app: selenium
        spec:
            volumes:
            - name: dshm
                emptyDir:
                medium: Memory
            containers:
            - name: selenium
              image: selenium/standalone-chrome:4.0
              volumeMounts:
              - mountPath: /dev/shm
                name: dshm
              ports:
              - containerPort: 4444
              readinessProbe:
                httpGet:
                    path: /
                    port: 4444
                initialDelaySeconds: 5
                periodSeconds: 5