apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: deploy-to-jenkins
subjects:
    - kind: ServiceAccount
      name: jenkins
roleRef:
    kind: Role
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io