apiVersion: v1
kind: Service
metadata:
  name: ingredient-service
  labels:
    app: ingredient-service
spec:
  type: ClusterIP
  selector:
    app: ingredient-service
  ports:
  - port: 8080
    targetPort: 80