apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: svc
resources:
- namespace.yaml
- ingress.yaml
bases:
- ../../services/mongo
- ../../services/jenkins
- ../../services/selenium