apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prd
resources:
- namespace.yaml
- ingress.yaml
bases:
- ../../services/blog
- ../../services/dinner-planner
- ../../services/ingredient-service
- ../../services/meal-service
- ../../jobs/mongo-setup