apiVersion: apps/v1
kind: Deployment
metadata:
  name: o-frontend
  labels:
    app: o-frontend
spec:
  selector:
    matchLabels:
      app: o-frontend
  template:
    metadata:
      labels:
        app: o-frontend
    spec:
      containers:
        - name: o-frontend
          image: berwoutv/o-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
